# logging.level.root: DEBUG      
logging:
  level:
    org.camunda: DEBUG
camunda:
  bpm:
    authorization:
      enabled: true
    # enabled: true
    process-engine-name: default
    database:
      type:
    admin-user:
      id: admin
      password: password
      firstName: admin
     
    filter:
      create: All tasks
    job-execution:
      lock-time-in-millis: 90000
