# logging.level.root: DEBUG      
logging:
  level:
    org.camunda: DEBUG
camunda:
  bpm:
    # enabled: true
    process-engine-name: default
    
    admin-user:
      id: hlex2
      password: notneed
      firstName: Mr.Demo
     
    filter:
      create: All tasks
    job-execution:
      lock-time-in-millis: 90000
