logging.level.root: DEBUG      
scamunda:
  bpm:
    # enabled: true
    process-engine-name: default
    
    admin-user:
      id: demo2
      password: demo2
      firstName: Mr.Demo
    filter:
      create: All tasks
    job-execution:
      lock-time-in-millis: 90000
